---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Set the sysconfig path for Debian systems
      set_fact:
        certbot_sysconfig_path: /etc/default/certbot
      when:
        - "ansible_distribution in ['Debian', 'Ubuntu']"

    - name: "Include ansible-role-certbot"
      include_role:
        name: "ansible-role-certbot"
      vars:
        certbot_pip_install: true
        certbot_pip_executable: /usr/bin/pip3
