---
- name: Install EPEL on CentOS releases
  package:
    name: epel-release
    state: present
    update_cache: true
  when:
    - "ansible_distribution|lower in ['centos']"
    - "not certbot_pip_install"

- name: Install Certbot packages
  package:
    name: >
      {{
        (certbot_packages is not none) |
        ternary(
          certbot_packages,
          (
            lookup(
              'vars',
              'certbot_packages_'+ansible_distribution|lower+ansible_distribution_major_version|string,
              default=''
            ) |
            ternary(
              lookup(
                'vars',
                'certbot_packages_'+ansible_distribution|lower+ansible_distribution_major_version|string,
                default=''
              ),
              lookup(
                'vars',
                'certbot_packages_'+ansible_distribution|lower
              )
            )
          )
        )
      }}
    state: present
  when:
    - "not certbot_pip_install"

- name: Install cronie for CentOS systems
  package:
    name: cronie
    state: present
  when:
    - "ansible_distribution|lower == 'CentOS'"

- name: Install some pip dependencies for doing openssl work in this role
  pip:
    name:
      - cryptography
      - pyopenssl
    state: present
    virtualenv: "{{ certbot_pip_virtualenv is not none | ternary(certbot_pip_virtualenv, omit) }}"
    virtualenv_command: "{{ certbot_pip_virtualenv_command | default(omit) }}"
    virtualenv_python: "{{ certbot_pip_virtualenv_python | default(omit) }}"
    virtualenv_site_packages: "{{ certbot_pip_virtualenv_site_packages is not none | ternary(certbot_pip_virtualenv_site_packages, omit) }}"
    executable: "{{ certbot_pip_executable | default(omit) }}"
  when:
    - >-
      (ansible_distribution != 'CentOS')
      or (ansible_distribution_major_version|int != 7)
