---
- name: Complain when attempting to install through pip on CentOS 7
  fail:
    msg: >-
      Using pip to do a standard certbot install on CentOS 7 isn't really
      supported by this role. This is due to the default python2 interpreter
      being too old for certbot. You can get around this by specifying a custom
      pip executable with `certbot_pip_executable`. It will just be assumed that
      you've picked a better pip executable (ie. pip3) that will work.
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version|int == 7"
    - "certbot_pip_executable is none"

# tasks file for ansible-role-certbot
- name: Load platform variables
  include_vars: "{{ filename }}"
  vars:
    vars_files:
      files:
        - "{{ role_path }}/vars/{{ ansible_distribution | lower }}/\
          {{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/vars/{{ ansible_distribution | lower }}/\
          main.yml"
        - "{{ role_path }}/vars/{{ ansible_os_family | lower }}/\
          main.yml"
        - "{{ role_path }}/vars/main.yml"
  loop: "{{ q('first_found', vars_files, errors='ignore') }}"
  loop_control:
    loop_var: filename

- name: Load platform dependencies
  vars:
    tasks:
      files:
        - "{{ role_path }}/tasks/dependencies/\
          {{ ansible_distribution | lower }}/\
          {{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/tasks/dependencies/\
          {{ ansible_distribution | lower }}/\
          main.yml"
        - "{{ role_path }}/tasks/dependencies/\
          {{ ansible_os_family | lower }}.yml"
        - "{{ role_path }}/tasks/dependencies/main.yml"
  include_tasks: "{{ filename }}"
  loop: "{{ q('first_found', tasks, errors='ignore') }}"
  loop_control:
    loop_var: filename

# Inexact guesswork at finding the certbot binary.
# virtualenv is virtualenv path + '/bin/certbot'
# no-virtualenv pip installs are /usr/local/bin/certbot
# everything else is /usr/bin/certbot which should be what is used by the distro
# package repo
- name: Set a single certbot command value based on the selected values
  set_fact:
    certbot_cmd: >-
      {{ (certbot_pip_install and (certbot_pip_virtualenv is not none) and (certbot_pip_virtualenv|length > 0)) |
         ternary(
           certbot_pip_virtualenv|string + '/bin/certbot',
           (
             (certbot_pip_install and (not certbot_pip_virtualenv)) |
             ternary(
              '/usr/local/bin/certbot',
              '/usr/bin/certbot',
             )
           )
         )
       }}
  tags:
    - certbot_bin
  when:
    - "certbot_cmd is none"

- name: Install packages
  include_tasks: install-packages.yml
  tags:
    - certbot_package
    - certbot_install
  when:
    - "not certbot_pip_install"

- name: Install certbot from source
  include_tasks: install-source.yml
  tags:
    - certbot_pip
    - certbot_install
  when:
    - "certbot_pip_install"

- name: Test that we actually got the correct cerbot bin path
  stat:
    path: "{{ certbot_cmd }}"
  tags:
    - certbot_bin

- name: Install certificate
  include_tasks: install-certificate.yml
  vars:
    email: "{{ certificate.email | default(certbot_email) }}"
    domains: "{{ certificate.domains }}"
  tags:
    - certbot_certificate
  loop: "{{ certbot_certificates }}"
  loop_control:
    loop_var: certificate

- name: Configure certbot renewal
  include_tasks: install-certificate-renewal-schedule.yml
  tags:
    - certbot_renewal
