---
# tasks file for dudefellah.certbot
- name: Gather role facts
  ansible.builtin.include_tasks: __c_gather_role_facts.yml
  tags:
    - certbot

- name: Fail if we haven't gotten a usable certbot command
  ansible.builtin.fail:
    msg: "No appropriate certbot cmd specified and/or found"
  when:
    - "_certbot_cmd is none"
  tags:
    - certbot

- name: Install EPEL release
  ansible.builtin.package:
    name: epel-release
    state: present
  when:
    - "ansible_os_family == 'RedHat'"
    - "certbot_el_install_epel|bool"
  tags:
    - certbot

- name: Install dependency packages
  ansible.builtin.package:
    name: "{{ _certbot_packages }}"
    state: present
  tags:
    - certbot

- name: Install PIP dependencies with the specified pip executable
  ansible.builtin.pip:
    name: "{{ _certbot_pip_modules }}"
    state: present
    executable: "{{ certbot_pip_executable | default(omit) }}"
  when:
    - "certbot_pip_install"
    - "_certbot_pip_modules is not none"
    - >-
      (certbot_pip_virtualenv is none) or (certbot_pip_virtualenv|length == 0)
  tags:
    - certbot

- name: Install PIP dependencies from virtualenv
  ansible.builtin.pip:
    name: "{{ _certbot_pip_modules }}"
    state: present
    virtualenv: "{{ certbot_pip_virtualenv | default(omit) }}"
    virtualenv_command: >-
      {{ certbot_pip_virtualenv_command | default(omit) }}
    virtualenv_python: >-
      {{ certbot_pip_virtualenv is not none
         | bool
         | ternary(certbot_pip_virtualenv_python, omit) }}
    virtualenv_site_packages: >-
      {{ certbot_pip_virtualenv is not none
         | bool
         | ternary(certbot_pip_virtualenv_site_packages, omit) }}
  when:
    - "certbot_pip_install"
    - "_certbot_pip_modules is not none"
    - "certbot_pip_virtualenv is not none"
    - "certbot_pip_virtualenv|length > 0"
  tags:
    - certbot

- name: Install the environment/defaults file
  ansible.builtin.template:
    src: certbot.sysconfig.j2
    dest: "{{ _certbot_sysconfig_path }}"
    owner: root
    group: root
    mode: "0644"
  tags:
    - certbot

- name: Install the systmed service
  ansible.builtin.template:
    src: certbot.service.j2
    dest: >-
      {{ certbot_renew_systemd_service_dir }}/\
      {{ certbot_renew_systemd_name }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - systemctl daemon-reload
  when:
    - "certbot_systemd_service_path is not none"
  tags:
    - molecule-notest
    - certbot

- name: Install the systemd timer
  ansible.builtin.template:
    src: certbot.timer.j2
    dest: >-
      {{ certbot_renew_systemd_service_dir }}/\
      {{ certbot_renew_systemd_name }}.timer
    owner: root
    group: root
    mode: "0644"
  notify:
    - systemctl daemon-reload
  when:
    - "certbot_systemd_service_path is not none"
    - "certbot_systemd_timer_path is not none"
  tags:
    - molecule-notest
    - certbot

- name: Install defined certificates
  include_tasks: __c_install_certificate.yml
  loop: "{{ certbot_certificates }}"
  loop_control:
    loop_var: __c_certificate
  tags:
    - certbot
