---
- name: Ensure other files are also present
  stat:
    path: "{{ certbot_etc_dir }}/live/{{ certificate.domains | first }}/{{ certfile }}"
  tags:
    - certbot_test
  loop:
    - cert.pem
    - privkey.pem
    - chain.pem
