---
- hosts: all
  gather_facts: false
  tasks:
    # Hacky little raw step to get all dependencies installed all at once
    - name: Install python
      raw: >
        {% if inventory_hostname in ['certbot-molecule-debian-buster-instance', 'certbot-molecule-ubuntu-20-04-instance', 'certbot-molecule-ubuntu-20-10-instance'] %}
        apt-get update && \
          DEBIAN_FRONTEND=noninteractive \
          apt-get -y install python3 \
            python3-apt \
            python3-pip \
            python3-setuptools \
            sudo \
            systemd \
            virtualenv
        {% elif inventory_hostname in ['certbot-molecule-debian-stretch-instance'] %}
        apt-get update && \
          DEBIAN_FRONTEND=noninteractive \
          apt-get -y install python \
            python-apt \
            python-pip \
            python-setuptools \
            python-virtualenv \
            systemd \
            sudo
        {% elif inventory_hostname in ['certbot-molecule-centos-8-instance'] %}
        yum -y install python3-pip python3-setuptools python3-virtualenv
        {% elif inventory_hostname in ['certbot-molecule-centos-7-instance'] %}
        yum -y install epel-release
        yum -y install python-pip python-setuptools python-virtualenv
        {% endif %}
