---
# handlers file for dudefellah.certbot
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen:
    - systemctl daemon-reload
  when:
    - "'molecule-converge-test' not in ansible_run_tags"
