---
# handlers file for ansible-role-certbot
- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  listen: systemctl daemon-reload

- name: Enable certbot.timer service with systemd
  systemd:
    name: certbot.timer
    enabled: true
    state: started
  listen: systemctl enable certbot.timer
  when:
    - "ansible_service_mgr == 'systemd'"

- name: Disable certbot.timer service with systemd
  systemd:
    name: certbot.timer
    enabled: false
    state: stopped
  listen: systemctl disable certbot.timer
  when:
    - "ansible_service_mgr == 'systemd'"
