---
# handlers file for ansible-role-certbot
- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  listen: systemctl daemon-reload

- name: Disable certbot.timer service with systemd
  systemd:
    name: certbot.timer
    state: stopped
    disabled: true
  listen: systemctl disable certbot.timer
  when:
    - "ansible_service_mgr == 'systemd'"
