---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: "Include ansible-role-certbot"
      include_role:
        name: "ansible-role-certbot"
      vars:
        certbot_pip_executable: >-
          {%- if (
            (ansible_distribution != 'CentOS')
            or (ansible_distribution_major_version|int != 7)
           ) -%}
            /usr/bin/pip3
          {%- else -%}
            {{ omit }}
          {%- endif -%}
