---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: "Include certbot"
      ansible.builtin.include_role:
        name: "ansible-role-certbot"
      tags:
        - molecule-converge-test
