---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: dudefellah.certbot-centos8-instance
    image: quay.io/centos/centos:stream8
provisioner:
  name: ansible
  options:
    tags: certbot,molecule-converge-test
  inventory:
    group_vars:
      all:
        certbot_el_install_epel: true
verifier:
  name: ansible
